### ISSUE TITLE
Private room – lobby - Start the game! gomb mindig aktív

### ISSUE THREAD

**Issue by holpertadrienn** [CaIlbackCats/codenames#8]
A Start the game! gomb mindig aktív, kattintható, de ha nem indítja el a játékot, akkor sincs hibaüzenet.
![cn_start](https://user-images.githubusercontent.com/66064945/83399693-ec9f3200-a401-11ea-8f6d-7722a55aa552.png)

**Comment by hudakelza** [comment]
Ezt a hibát azóta nem sikerült újragenerálni, ugye?

**Comment by holpertadrienn** [comment]
Nem, ez már jó. :)

**Comment by hudakelza** [comment]
Köszi :)
